#!/usr/bin/env python3
"""Compact current-state summary, generated live from the project-control ledger.

The ledger (`project-control/`) plus git/CI is the single source of truth. This script is a
read-only *view* of it — it stores nothing, so it can never drift. Run it instead of maintaining a
hand-written status board (which is exactly what went stale in docs/IMPLEMENTATION_STATUS.md and
docs/MASTER_EXECUTION_PLAN.md).

Usage:
    python tools/current_state.py            # human-readable Markdown to stdout
    python tools/current_state.py --json      # machine-readable JSON

Stdlib only (thin-client / CI safe). No network, no writes.
"""
from __future__ import annotations

import json
import pathlib
import sys
from collections import Counter, defaultdict

ROOT = pathlib.Path(__file__).resolve().parent.parent
PC = ROOT / "project-control"


def _load(path: pathlib.Path):
    return json.loads(path.read_text(encoding="utf-8"))


def collect() -> dict:
    tasks = []
    for f in sorted((PC / "tasks").glob("*.json")):
        try:
            d = _load(f)
        except Exception as e:  # pragma: no cover - defensive
            print(f"WARN: cannot parse {f}: {e}", file=sys.stderr)
            continue
        tasks.append(d)

    state = _load(PC / "state.json") if (PC / "state.json").exists() else {}

    blockers = []
    for f in sorted((PC / "blockers").glob("*.json")):
        try:
            b = _load(f)
        except Exception:
            continue
        if str(b.get("status", "")).lower() == "open":
            blockers.append(b)

    checkpoints = sorted((PC / "checkpoints").glob("CP-*.json"))
    latest_cp = checkpoints[-1].stem if checkpoints else state.get("last_checkpoint", "?")

    status_counts = Counter(t.get("status", "?") for t in tasks)
    by_ms_total: dict[str, int] = defaultdict(int)
    by_ms_accepted: dict[str, int] = defaultdict(int)
    active = []
    for t in tasks:
        ms = t.get("milestone_id") or (t.get("task_id", "?").split("-")[0])
        by_ms_total[ms] += 1
        if t.get("status") == "accepted":
            by_ms_accepted[ms] += 1
        elif t.get("status") in ("claimed", "in_progress", "awaiting_gate", "self_check", "rework"):
            active.append(t)

    return {
        "project_status": state.get("project_status", "?"),
        "current_milestone": state.get("current_milestone", "?"),
        "latest_checkpoint": latest_cp,
        "updated_at": state.get("updated_at", "?"),
        "total_tasks": len(tasks),
        "status_counts": dict(sorted(status_counts.items())),
        "milestones": {
            ms: {"accepted": by_ms_accepted.get(ms, 0), "total": by_ms_total[ms]}
            for ms in sorted(by_ms_total)
        },
        "active_tasks": [
            {
                "task_id": t.get("task_id"),
                "status": t.get("status"),
                "agent": t.get("producer_agent"),
                "progress": t.get("progress_percent"),
                "worktree": t.get("worktree"),
            }
            for t in sorted(active, key=lambda x: x.get("task_id", ""))
        ],
        "open_blockers": [
            {"id": b.get("blocker_id"), "title": b.get("title")}
            for b in blockers
        ],
    }


def to_markdown(s: dict) -> str:
    counts = " / ".join(f"{v} {k}" for k, v in s["status_counts"].items())
    lines = [
        "# Current state (generated from the ledger)",
        "",
        "> Generated by `python tools/current_state.py`. Do not hand-edit - it is a live view of "
        "`project-control/`. The ledger + git/CI are authoritative.",
        "",
        f"- **Project:** {s['project_status']}  |  **Milestone:** {s['current_milestone']}  "
        f"|  **Checkpoint:** {s['latest_checkpoint']}  |  **Ledger updated:** {s['updated_at']}",
        f"- **Tasks ({s['total_tasks']}):** {counts}",
        "",
        "## Milestones (accepted / total tasks)",
        "",
        "| Milestone | Accepted | Total |",
        "|---|---|---|",
    ]
    for ms, m in s["milestones"].items():
        lines.append(f"| {ms} | {m['accepted']} | {m['total']} |")
    lines += ["", "## Active (non-accepted, in-flight) tasks", ""]
    if s["active_tasks"]:
        lines += ["| Task | Status | Producer | % | Worktree |", "|---|---|---|---|---|"]
        for t in s["active_tasks"]:
            lines.append(
                f"| {t['task_id']} | {t['status']} | {t.get('agent') or '-'} | "
                f"{t.get('progress') if t.get('progress') is not None else '-'} | "
                f"{t.get('worktree') or '-'} |"
            )
    else:
        lines.append("_None._")
    lines += ["", "## Open blockers", ""]
    if s["open_blockers"]:
        for b in s["open_blockers"]:
            lines.append(f"- **{b['id']}** - {b['title']}")
    else:
        lines.append("_None._")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    s = collect()
    if "--json" in argv:
        print(json.dumps(s, indent=2))
    else:
        print(to_markdown(s))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
